version: '3.9'

services:
  mysql:
      image: postgres
      container_name: postgres
      environment:
        - "DATABASE=order_management"
        - "USERNAME=postgres"
        - "PASSWORD=00112233"
      ports:
        - "127.0.0.1:5433:5433"
      volumes:
        - C:/M.kharma_data/bzu/WebServices2022/docker/data/mysql:/var/lib/postgres
  app:
    image: 'rest-api:latest'
    container_name: rest-api
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:jdbc:postgresql://localhost:5433/order_management?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=00112233
      - SERVER_PORT=8082
    ports:
      - "127.0.0.1:8082:8082"