# its yaml file to create containers
# docker-compose up  to start containers in the background.
version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=00112233
      - POSTGRES_DB=recipe
    ports:
      - '5433:5433'

  recipe:
    container_name: recipe_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8083:8084'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5433/order_management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=00112233
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db